version: '3.7'

services:
  psql:
    image: postgres:15
    container_name: 'psql'
    volumes:
      - ../migrations/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres


  app:
    container_name: 'app'
    build:
      context: ../
      dockerfile: deployments/Dockerfile
    restart: on-failure
    ports:
      - '9000:9000'

